services:
  db: 
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Wordpass12
  : 
    image: nginx
    volumes: 
      - ./:/usr/share/nginx/html:ro